"""adding token and password field

Revision ID: a4f102cf26e3
Revises: 95282360b30e
Create Date: 2024-02-20 17:11:24.461396

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4f102cf26e3"
down_revision: Union[str, None] = "95282360b30e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.String(length=25), nullable=False))
    op.add_column("user", sa.Column("token", sa.Text(), nullable=True))
    op.create_unique_constraint(None, "user", ["token"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "token")
    op.drop_column("user", "password")
    # ### end Alembic commands ###
